MAKEFILE = Makefile.win

all:
	for dir in swe base dialogs views wxpdfdoc wxJSON wxsqlite3 jyotish gui; do \
		cd $$dir; \
		mingw32-make -f $(MAKEFILE) || exit 1; \
		cd ..; \
	done

clean:
	for dir in swe base dialogs views wxpdfdoc wxJSON wxsqlite3 jyotish gui; do \
		cd $$dir; \
		mingw32-make -f $(MAKEFILE) clean; \
		cd ..; \
	done



